[#162053529] Add endpoints balance, instruments and trade
ArizenHQ/b2c2-client pull request #1
Opened 2018-11-21 15:11 UTC by BGuimberteau

Now you can :
get :
- the balance
- the instruments
post :
- a trade

2018-11-21 15:29 UTC, shideneyu approved these changes
Great, I love it ! Nice understanding and usage of the pattern I created. Nice quality code too.

2018-11-27 14:22 UTC, vrenaudineau requested changes
Complete README with new calls

2018-11-27 14:22 UTC, vrenaudineau commented on lib/b2c2_client/requests/base.rb
> +      def initialize(config, options = {})
GET requests should not require an empty params. Override ?

2018-11-27 17:07 UTC, vrenaudineau approved these changes

2018-11-27 17:12 UTC, merged